version: '2'

networks:
  default:
    driver: bridge

volumes:
  geoserver-data:
    driver: local

services:

  geoserver:
    build: .
    container_name: geoserver
    hostname: geoserver
    restart: always
#    ports:
#      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: "20m"

